all: help

help:
	@echo ""
	@echo "-- Help Menu"
	@echo ""
	@echo "   1. make build            - build all images"
	@echo "   1. make clean            - remove all images"
	@echo ""

build:
	@docker build --tagosrf/ros:melodic-rviz .

clean:
	@docker rmi -f osrf/ros:melodic-rviz
